### ISSUE TITLE
Create API for Movie Posters

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/poster-service#11]
### Related User Story & Issues
Story: https://github.com/kwizapp/kwiz/issues/22

### Description
Add API endpoint that returns a movie poster for a given IMDb id.

### Tasks
- [x] cleanup old code
- [x] add `GET` for `/poster`
- [x] query omdb for the provided IMBd id 
- [x] return the `Poster` key which contains the poster url
- [x] add url parameter to specify what size of the image is requested
    - no parameter = default size
    - number between 300 and 1000
