### ISSUE TITLE
Integrate kwiz-utils library

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/poster-service#13]
### Description

Use the newly created `kwiz-util` repository which was extracted in it's own library. The library provides the validation function that the `poster-service` needs.

### Tasks

- [x] install `npm i @kwizapp/kwiz-utils`
- [x] replace existing validation with functionality provided by `kwiz-utils` 
- [x] remove the now redundant tests (the unit tests of the validation functions)
- [x] update GitHub actions workflow to properly install from github package registry

### Context 
[Story: Poster API](https://github.com/kwizapp/kwiz/issues/22)
